### ISSUE TITLE
Update @react-native-async-storage/async-storage@1.21.0

### ISSUE THREAD

**Issue by eruveo** [bothrs/i18next-async-storage-backend2#2]
Hi, can we bump up the async to 1.21?

<img width="648" alt="Screenshot 2024-03-22 at 1 14 29 am" src="https://github.com/bothrs/i18next-async-storage-backend2/assets/5385334/42c35ae9-b037-479a-981d-6276b440cdea">

**Comment by thgh** [comment]
Released in v2.1.0 🎉
